# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_retail
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Duy171103 # <-- THAY MẬT KHẨU CỦA BẠN VÀO ĐÂY
      MYSQL_DATABASE: retail_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: