# .github/workflows/ci.yml
name: Python CI

# Workflow này sẽ chạy mỗi khi có code được push hoặc có pull request tới branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Chạy trên một máy ảo Ubuntu phiên bản mới nhất
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"] # Chạy với Python 3.9

    steps:
    # Bước 1: Checkout code từ repository về máy ảo
    - uses: actions/checkout@v3

    # Bước 2: Thiết lập môi trường Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Bước 3: Cài đặt các thư viện cần thiết, bao gồm cả flake8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Bước 4: Chạy linter (flake8) để kiểm tra code
    - name: Lint with flake8
      run: |
        # --count: đếm số lỗi
        # --select=E9,F63,F7,F82: chỉ dừng build nếu có lỗi nghiêm trọng
        # --show-source --statistics: hiển thị chi tiết lỗi
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics